#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "eric-oss-rim-poc.fullname" . }}
  labels:
  {{- include "eric-oss-rim-poc.labels" . | nindent 4 }}
  annotations:
  {{- $prometheus := (merge (dict "additionalAnnotations" (include "eric-oss-rim-poc.prometheus" . | fromYaml)) .) -}}
  {{- include "eric-oss-rim-poc.annotations" $prometheus | nindent 4 }}
spec:
{{- if not .Values.autoScaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  serviceName: {{ include "eric-oss-rim-poc.fullname" . }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eric-oss-rim-poc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  updateStrategy:
    type: {{ .Values.updateStrategy.type | quote }}
  template:
    metadata:
      labels:
        {{- $streaming := default (include "eric-oss-rim-poc.directStreamingLabel" . | fromYaml) dict -}}
        {{- $label := (merge (dict "additionalLabels" (set $streaming "eric-data-object-storage-mn-access" "true")) .) }}
        {{- include "eric-oss-rim-poc.labels" $label | nindent 8 }}
        {{- include "eric-oss-rim-poc.directStreamingLabel" . | nindent 8 }}
      annotations:
        {{- include "eric-oss-rim-poc.annotations" $prometheus | nindent 8 }}
        {{- include "eric-oss-rim-poc.container-annotations" . | nindent 8 }}
    spec:
      {{- if include "eric-oss-rim-poc.pullSecret" . }}
      imagePullSecrets:
        - name: {{ include "eric-oss-rim-poc.pullSecret" . | quote}}
      {{- end }}
      serviceAccountName: {{ template "eric-oss-rim-poc.fullname" . }}
      securityContext:
        fsGroup: {{ include "eric-oss-rim-poc.fsGroup.coordinated" . }}
        runAsUser: {{ include "eric-oss-rim-poc.runAsUser.coordinated" . }}
        {{- include "eric-oss-rim-poc.seccomp-profile" . | indent 8 }}
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: target-volume
          emptyDir: {}
        - name: config-volume
          configMap:
            defaultMode: 493
            name: {{ include "eric-oss-rim-poc.name" . }}-configmap
      containers:
        - name: eric-oss-rim-poc
          image: {{ template "eric-oss-rim-poc.mainImagePath" . }}
          imagePullPolicy: {{ template "eric-oss-rim-poc.registryImagePullPolicy" . }}
          securityContext:
            runAsUser: {{ include "eric-oss-rim-poc.runAsUser.coordinated" . }}
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - all
          volumeMounts:
            {{- if .Values.persistentStorage.dbVolume.enabled }}
            - mountPath: /h2db
              name: dbVolume
            {{- end }}
            - mountPath: /tmp
              name: tmp-volume
            - mountPath: /target
              name: target-volume
            - name: config-volume
              mountPath: /config
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: jdbc
              containerPort: 9090
              protocol: TCP
          livenessProbe:
          {{- if (index .Values "probes" "eric-oss-rim-poc" "livenessProbe" "initialDelaySeconds") }}
            {{ print "initialDelaySeconds: " (index .Values "probes" "eric-oss-rim-poc" "livenessProbe" "initialDelaySeconds") }}
          {{- end }}
          {{- if (index .Values "probes" "eric-oss-rim-poc" "livenessProbe" "failureThreshold") }}
            {{ print "failureThreshold: " (index .Values "probes" "eric-oss-rim-poc" "livenessProbe" "failureThreshold") }}
          {{- end }}
          {{- if (index .Values "probes" "eric-oss-rim-poc" "livenessProbe" "periodSeconds") }}
            {{ print "periodSeconds: " (index .Values "probes" "eric-oss-rim-poc" "livenessProbe" "periodSeconds") }}
          {{- end }}
          {{- if (index .Values "probes" "eric-oss-rim-poc" "livenessProbe" "timeoutSeconds") }}
            {{ print "timeoutSeconds: " (index .Values "probes" "eric-oss-rim-poc" "livenessProbe" "timeoutSeconds") }}
          {{- end }}
            httpGet:
              path: /actuator/health
              port: http
          readinessProbe:
          {{- if (index .Values "probes" "eric-oss-rim-poc" "readinessProbe" "initialDelaySeconds") }}
            {{ print "initialDelaySeconds: " (index .Values "probes" "eric-oss-rim-poc" "readinessProbe" "initialDelaySeconds") }}
          {{- end }}
          {{- if (index .Values "probes" "eric-oss-rim-poc" "readinessProbe" "failureThreshold") }}
            {{ print "failureThreshold: " (index .Values "probes" "eric-oss-rim-poc" "readinessProbe" "failureThreshold") }}
          {{- end }}
          {{- if (index .Values "probes" "eric-oss-rim-poc" "readinessProbe" "periodSeconds") }}
            {{ print "periodSeconds: " (index .Values "probes" "eric-oss-rim-poc" "readinessProbe" "periodSeconds") }}
          {{- end }}
          {{- if (index .Values "probes" "eric-oss-rim-poc" "readinessProbe" "timeoutSeconds") }}
            {{ print "timeoutSeconds: " (index .Values "probes" "eric-oss-rim-poc" "readinessProbe" "timeoutSeconds") }}
          {{- end }}
            httpGet:
              path: /actuator/health
              port: http
          env:
          - name: JAVA_OPTS
            value: {{ include "eric-oss-rim-poc.jvmHeapSettings" . }}
          - name: TZ
            value: {{ template "eric-oss-rim-poc.timezone" . }}
          - name: BDR_ACCESSKEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.objectStorage.secretName }}
                key: {{ .Values.objectStorage.accessKeyName }}
          - name: BDR_SECRETKEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.objectStorage.secretName }}
                key: {{ .Values.objectStorage.secretKeyName }}
          - name: CTS_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.client.cts.login.secretName }}
                key: {{ .Values.client.cts.login.username }}
          - name: CTS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.client.cts.login.secretName }}
                key: {{ .Values.client.cts.login.password }}
          - name: NCMP_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.client.ncmp.login.secretName }}
                key: {{ .Values.client.ncmp.login.username }}
          - name: NCMP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.client.ncmp.login.secretName }}
                key: {{ .Values.client.ncmp.login.password }}
      {{- if .Values.global }}
        {{- if .Values.global.security }}
          {{- if .Values.global.security.tls }}
            {{- if .Values.global.security.tls.enabled }}
          - name: CONNECT_MODE
            value: "tls"
            {{- if (eq .Values.service.endpoints.chassisapi.tls.enforced "required") }}
          - name: TLS_MODE
            value: "only_tls"
            {{- if (eq .Values.service.endpoints.chassisapi.tls.verifyClientCertificate "required") }}
          - name: TLS_CA
            value: "ca_path"
            {{- end }}
            {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
          resources:
            requests:
            {{- if (index .Values "resources" "eric-oss-rim-poc" "requests" "cpu") }}
              cpu: {{ (index .Values "resources" "eric-oss-rim-poc" "requests" "cpu" | quote) }}
            {{- end }}
            {{- if (index .Values "resources" "eric-oss-rim-poc" "requests" "memory") }}
              memory: {{ (index .Values "resources" "eric-oss-rim-poc" "requests" "memory" | quote) }}
            {{- end }}
            {{- if (index .Values "resources" "eric-oss-rim-poc" "requests" "ephemeral-storage") }}
            {{ println "  ephemeral-storage:" (index .Values "resources" "eric-oss-rim-poc" "requests" "ephemeral-storage" | quote) }}
            {{- end }}
            limits:
            {{- if (index .Values "resources" "eric-oss-rim-poc" "limits" "cpu") }}
              cpu: {{ (index .Values "resources" "eric-oss-rim-poc" "limits" "cpu" | quote) }}
            {{- end }}
            {{- if (index .Values "resources" "eric-oss-rim-poc" "limits" "memory") }}
              memory: {{ (index .Values "resources" "eric-oss-rim-poc" "limits" "memory" | quote) }}
            {{- end }}
            {{- if (index .Values "resources" "eric-oss-rim-poc" "limits" "ephemeral-storage") }}
            {{ println "  ephemeral-storage:" (index .Values "resources" "eric-oss-rim-poc" "limits" "ephemeral-storage" | quote) }}
            {{- end }}
      nodeSelector: {{ include "eric-oss-rim-poc.nodeSelector" . | nindent 6 -}}

      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds:
        {{- include "eric-oss-rim-poc.terminationGracePeriodSeconds" . | nindent 8 }}
      {{- end }}

      {{- if .Values.tolerations }}
      tolerations:
        {{- include "eric-oss-rim-poc.tolerations" . | nindent 8 }}
      {{- end }}

      {{- if (index .Values "podPriority" "eric-oss-rim-poc" "priorityClassName") }}
      priorityClassName: {{ (index .Values "podPriority" "eric-oss-rim-poc" "priorityClassName") }}
      {{- end }}

      {{- with .Values.topologySpreadConstraints.deployment }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if eq .Values.affinity.podAntiAffinity "hard" }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ include "eric-oss-rim-poc.name" . }}
            topologyKey: "kubernetes.io/hostname"
      {{- else if eq .Values.affinity.podAntiAffinity  "soft" }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ include "eric-oss-rim-poc.name" . }}
              topologyKey: "kubernetes.io/hostname"
      {{- end }}
  {{- if .Values.persistentStorage.dbVolume.enabled }}
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: dbVolume
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.persistentStorage.dbVolume.persistentVolumeClaim.storageClassName }}
        storageClassName: {{ .Values.persistentStorage.dbVolume.persistentVolumeClaim.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ default .Values.persistentStorage.dbVolume.persistentVolumeClaim.size .Values.persistentVolumeClaim.size }}
  {{- end }}
